import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

/* ───── Translations Data ────────────────────── */
const translations = {
  en: {
    dashboard: 'Dashboard',
    nearbyHospitals: 'Nearby Hospitals',
    mapView: 'Map View',
    savedHospitals: 'Saved Hospitals',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    active: 'Active',
    emergencyHelp: 'Emergency Help',
    emergencyDesc: 'Need an ambulance quickly?',
    emergencySub: 'Emergency services available across India.',
    call108: 'Call 108',
    findHospitals: 'Find Emergency Hospitals',
    searchPlaceholder: 'Search hospitals, doctors...',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    save: 'Save',
    cancel: 'Cancel',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    bio: 'Bio',
    memberSince: 'Member Since',
    account: 'Account',
    verified: 'Verified',
    hospitalsNearby: 'Hospitals Nearby',
    topRated: 'Top Rated',
    specializations: 'Specializations',
    quickServices: 'Quick Services',
    bookAppointment: 'Book Appointment',
    findDoctors: 'Find Doctors',
    nearbyPharmacy: 'Nearby Pharmacy',
    diagnosticLabs: 'Diagnostic Labs',
    mainMenu: 'Main Menu',
    changeLocation: 'Change Location',
    locationUnknown: 'Location Unknown',
    findHospitalsMap: 'Find Hospitals Map',
    hospitalNearbyFound: 'hospitals around you',
    openLiveMap: 'Open Live Map',
    currentRegion: 'CURRENT REGION',
    viewAll: 'View all',
    detecting: 'Detecting...',
    appearance: 'Appearance',
    notifications: 'Notifications',
    privacy: 'Privacy & Security',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    darkMode: 'Dark Mode',
    language: 'Language',
    saveChanges: 'Save Changes',
    saved: 'Saved!',
    deleteAccountTitle: 'Delete Account?',
    deleteAccountConfirmDesc: 'This action is permanent and irreversible. Your account, saved hospitals, and all data will be permanently deleted.',
    deleteAccountTypeConfirm: 'Type delete to confirm:',
    deleteAccountPlaceholder: 'Type delete here...',
    cancelDelete: 'Cancel',
    confirmDeleteBtn: 'Delete Account',
    choosePreferredLanguage: 'Choose your preferred language',
    logoutDesc: 'Sign out from your account',
    deleteAccountDesc: 'Permanently delete all your data — this cannot be undone',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Get notified about hospital updates',
    emailAlerts: 'Email Alerts',
    emailAlertsDesc: 'Receive weekly health tips via email',
    locationAccess: 'Location Access',
    locationAccessDesc: 'Allow MediGuide to detect your location',
    twoFactor: 'Two-Factor Authentication',
    twoFactorDesc: 'Extra security for your account',
    anonymousDataSharing: 'Anonymous Data Sharing',
    anonymousDataSharingDesc: 'Help us improve MediGuide',
    savedHospitalsLabel: 'Saved Hospitals',
    verifiedLabel: 'Verified',
    findHospitalsGeneric: 'Find Hospitals',
    hospitalsFoundMsg: 'hospitals found',
    searching: 'Searching...',
    clearAll: 'Clear all',
    filters: 'Filters',
    advancedFilters: 'Advanced Filters',
    specialization: 'Specialization',
    minRating: 'Min Rating',
    costRange: 'Cost Range',
    noHospitalsFound: 'No hospitals found',
    adjustSearch: 'Try adjusting your search terms or clearing the filters.',
    clearFilters: 'Clear Filters',
    prev: 'Prev',
    next: 'Next',
    openMapView: 'Open Map View',
    sortDistance: 'Sort: Distance',
    sortRating: 'Sort: Rating',
    sortCostLow: 'Sort: Cost (Low)',
    searchExtended: 'Search hospitals, symptoms, or city...',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    nearbyHospitals: 'आस-पास के अस्पताल',
    mapView: 'मैप व्यू',
    savedHospitals: 'सहेजे गए अस्पताल',
    profile: 'प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    active: 'सक्रिय',
    emergencyHelp: 'आपातकालीन सहायता',
    emergencyDesc: 'जल्दी एम्बुलेंस चाहिए?',
    emergencySub: 'पूरे भारत में आपातकालीन सेवाएं उपलब्ध हैं।',
    call108: '108 पर कॉल करें',
    findHospitals: 'आपातकालीन अस्पताल खोजें',
    searchPlaceholder: 'अस्पताल, डॉक्टर खोजें...',
    myProfile: 'मेरी प्रोफाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    phone: 'फ़ोन',
    city: 'शहर',
    bio: 'बायो',
    memberSince: 'सदस्यता की तिथि',
    account: 'खाता',
    verified: 'सत्यापित',
    hospitalsNearby: 'पास के अस्पताल',
    topRated: 'शीर्ष रेटेड',
    specializations: 'विशेषज्ञता',
    quickServices: 'त्वरित सेवाऐं',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    findDoctors: 'डॉक्टर खोजें',
    nearbyPharmacy: 'पास की फार्मेसी',
    diagnosticLabs: 'डायग्नोस्टिक लैब्स',
    mainMenu: 'मुख्य मेनू',
    changeLocation: 'स्थान बदलें',
    locationUnknown: 'अज्ञात स्थान',
    findHospitalsMap: 'मैप पर खोजें',
    hospitalNearbyFound: 'आपके आस-पास के अस्पताल',
    openLiveMap: 'लाइव मैप खोलें',
    currentRegion: 'वर्तमान क्षेत्र',
    viewAll: 'सभी देखें',
    detecting: 'पता लगा रहे हैं...',
    appearance: 'दिखावट',
    notifications: 'सूचनाएं',
    privacy: 'गोपनीयता और सुरक्षा',
    dangerZone: 'खतरा क्षेत्र',
    deleteAccount: 'खाता हटाएं',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    saveChanges: 'परिवर्तन सहेजें',
    saved: 'सहेजा गया!',
    deleteAccountTitle: 'खाता हटाएं?',
    deleteAccountConfirmDesc: 'यह क्रिया स्थायी और अपरिवर्तनीय है। आपका खाता, सहेजे गए अस्पताल और सभी डेटा स्थायी रूप से हटा दिए जाएंगे।',
    deleteAccountTypeConfirm: 'पुष्टि करने के लिए delete टाइप करें:',
    deleteAccountPlaceholder: 'यहाँ delete टाइप करें...',
    cancelDelete: 'रद्द करें',
    confirmDeleteBtn: 'खाता हटाएं',
    choosePreferredLanguage: 'अपनी पसंदीदा भाषा चुनें',
    logoutDesc: 'अपने खाते से साइन आउट करें',
    deleteAccountDesc: 'अपना सारा डेटा स्थायी रूप से हटा दें - इसे पूर्ववत नहीं किया जा सकता',
    pushNotifications: 'पुश नोटिफिकेशन',
    pushNotificationsDesc: 'अस्पताल अपडेट के बारे में सूचित रहें',
    emailAlerts: 'ईमेल अलर्ट',
    emailAlertsDesc: 'ईमेल के माध्यम से साप्ताहिक स्वास्थ्य युक्तियाँ प्राप्त करें',
    locationAccess: 'स्थान पहुंच',
    locationAccessDesc: 'MediGuide को आपके स्थान का पता लगाने की अनुमति दें',
    twoFactor: 'दो-कारक प्रमाणीकरण',
    twoFactorDesc: 'आपके खाते के लिए अतिरिक्त सुरक्षा',
    anonymousDataSharing: 'अनाम डेटा साझाकरण',
    anonymousDataSharingDesc: 'हमें MediGuide को बेहतर बनाने में मदद करें',
    savedHospitalsLabel: 'सहेजे गए अस्पताल',
    verifiedLabel: 'सत्यापित',
    findHospitalsGeneric: 'अस्पताल खोजें',
    hospitalsFoundMsg: 'अस्पताल मिले',
    searching: 'खोज रहे हैं...',
    clearAll: 'सभी साफ करें',
    filters: 'फिल्टर',
    advancedFilters: 'उन्नत फिल्टर',
    specialization: 'विशेषज्ञता',
    minRating: 'न्यूनतम रेटिंग',
    costRange: 'लागत सीमा',
    noHospitalsFound: 'कोई अस्पताल नहीं मिला',
    adjustSearch: 'खोज शब्दों को बदलने या फिल्टर साफ करने का प्रयास करें।',
    clearFilters: 'फ़िल्टर साफ करें',
    prev: 'पिछला',
    next: 'अगला',
    openMapView: 'मैप व्यू खोलें',
    sortDistance: 'क्रम: दूरी',
    sortRating: 'क्रम: रेटिंग',
    sortCostLow: 'क्रम: लागत (कम)',
    searchExtended: 'अस्पताल, लक्षण या शहर खोजें...',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    nearbyHospitals: 'નજીકની હોસ્પિટલો',
    mapView: 'મેપ વ્યૂ',
    savedHospitals: 'સાચવેલી હોસ્પિટલો',
    profile: 'પ્રોફાઇલ',
    settings: 'સેટિંગ્સ',
    logout: 'લૉગઆઉટ',
    active: 'સક્રિય',
    emergencyHelp: 'કટોકટીની મદદ',
    emergencyDesc: 'ઝડપથી એમ્બ્યુલન્સની જરૂર છે?',
    emergencySub: 'સમગ્ર ભારતમાં કટોકટીની સેવાઓ ઉપલબ્ધ છે.',
    call108: '108 પર કોલ કરો',
    findHospitals: 'કટોકટી હોસ્પિટલો શોધો',
    searchPlaceholder: 'હોસ્પિટલો, ડૉક્ટરો શોધો...',
    myProfile: 'મારી પ્રોફાઇલ',
    editProfile: 'પ્રોફાઇલ એડિટ કરો',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    fullName: 'પૂરું નામ',
    email: 'ઈમેલ',
    phone: 'ફોન',
    city: 'શહેર',
    bio: 'બાયો',
    memberSince: 'સભ્યપદ તારીખ',
    account: 'ખાતું',
    verified: 'ચકાસાયેલ',
    hospitalsNearby: 'નજીકની હોસ્પિટલો',
    topRated: 'ટોપ રેટેડ',
    specializations: 'વિશેષતા',
    quickServices: 'ઝડપી સેવાઓ',
    bookAppointment: 'એપોઈન્ટમેન્ટ બુક કરો',
    findDoctors: 'ડોકટરો શોધો',
    nearbyPharmacy: 'નજીકની ફાર્મસી',
    diagnosticLabs: 'નિદાન લેબ્સ',
    mainMenu: 'મુખ્ય મેનુ',
    changeLocation: 'સ્થાન બદલો',
    locationUnknown: 'અજ્ઞાત સ્થાન',
    findHospitalsMap: 'નજીકની હોસ્પિટલ શોધો',
    hospitalNearbyFound: 'તમારી આસપાસની હોસ્પિટલો',
    openLiveMap: 'લાઇવ મેપ ખોલો',
    currentRegion: 'વર્તમાન પ્રદેશ',
    viewAll: 'બધું જુઓ',
    detecting: 'શોધી રહ્યાં છીએ...',
    appearance: 'દેખાવ',
    notifications: 'સૂચનાઓ',
    privacy: 'ગોપનીયતા અને સુરક્ષા',
    dangerZone: 'ખતરો ઝોન',
    deleteAccount: 'ખાતું કાઢી નાખો',
    darkMode: 'ડાર્ક મોડ',
    language: 'ભાષા',
    saveChanges: 'ફેરફારો સાચવો',
    saved: 'સાચવ્યું!',
    deleteAccountTitle: 'ખાતું કાઢી નાખવું છે?',
    deleteAccountConfirmDesc: 'આ ક્રિયા કાયમી અને અપરિવર્તનીય છે. તમારું ખાતું, સાચવેલી હોસ્પિટલો અને તમામ ડેટા કાયમી ધોરણે કાઢી નાખવામાં આવશે.',
    deleteAccountTypeConfirm: 'પુષ્ટિ કરવા માટે delete ટાઇપ કરો:',
    deleteAccountPlaceholder: 'અહીં delete ટાઇપ કરો...',
    cancelDelete: 'રદ કરો',
    confirmDeleteBtn: 'ખાતું કાઢી નાખો',
    choosePreferredLanguage: 'તમારી પસંદગીની ભાષા પસંદ કરો',
    logoutDesc: 'તમારા ખાતામાંથી સાઇન આઉટ કરો',
    deleteAccountDesc: 'તમારો બધો ડેટા કાયમી ધોરણે કાઢી નાખો - આ પાછું ખેંચી શકાશે નહીં',
    pushNotifications: 'પુશ સૂચનાઓ',
    pushNotificationsDesc: 'હોસ્પિટલ અપડેટ્સ વિશે સૂચિત રહો',
    emailAlerts: 'ઈમેલ ચેતવણીઓ',
    emailAlertsDesc: 'ઈમેલ દ્વારા સાપ્તાહિક આરોગ્ય ટિપ્સ મેળવો',
    locationAccess: 'સ્થાન ઍક્સેસ',
    locationAccessDesc: 'MediGuide ને તમારું સ્થાન શોધવાની મંજૂરી આપો',
    twoFactor: 'દ્વિ-પરિબળ પ્રમાણીકરણ',
    twoFactorDesc: 'તમારા ખાતા માટે વધારાની સુરક્ષા',
    anonymousDataSharing: 'અનામી ડેટા શેરિંગ',
    anonymousDataSharingDesc: 'અમને MediGuide સુધારવામાં મદદ કરો',
    savedHospitalsLabel: 'સાચવેલી હોસ્પિટલો',
    verifiedLabel: 'ચકાસાયેલ',
    findHospitalsGeneric: 'હોસ્પિટલો શોધો',
    hospitalsFoundMsg: 'હોસ્પિટલો મળી',
    searching: 'શોધી રહ્યાં છીએ...',
    clearAll: 'બધું સાફ કરો',
    filters: 'ફિલ્ટર્સ',
    advancedFilters: 'અદ્યતન ફિલ્ટર્સ',
    specialization: 'વિશેષતા',
    minRating: 'ન્યૂનતમ રેટિંગ',
    costRange: 'ખર્ચ મર્યાદા',
    noHospitalsFound: 'કોઈ હોસ્પિટલ મળી નથી',
    adjustSearch: 'શોધ શબ્દો બદલવાનો અથવા ફિલ્ટર્સ સાફ કરવાનો પ્રયાસ કરો.',
    clearFilters: 'ફિલ્ટર્સ સાફ કરો',
    prev: 'અગાઉનું',
    next: 'પછીનું',
    openMapView: 'મેપ વ્યૂ ખોલો',
    sortDistance: 'ક્રમ: અંતર',
    sortRating: 'ક્રમ: રેટિંગ',
    sortCostLow: 'ક્રમ: ખર્ચ (ઓછો)',
    searchExtended: 'હોસ્પિટલો, લક્ષણો અથવા શહેર શોધો...',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('mediguide_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('mediguide_lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
